version: '3'
services: 
    app:
        container_name: docker-node-postgres
        restart: always
        build: .
        ports:
            - "8080:5000"
        links:
            - postgres

    postgres:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: postgres
